### ISSUE TITLE
Using wmfocus to kill applications?

### ISSUE THREAD

**Issue by xpenguinclub** [svenstaro/wmfocus#10]
Hello,

I have come to wmfocus from i3-easy focus, i mostly use it to kill things. using i3-focus i can the the following

     i3-easyfocus | xargs xkill -id

however when i try to swap out i3-easy-focus for wmfocus i get the error 'xkill requires  an argument' 

I am not a coder and have no idea how to resolve this but give that both applications perform the same job i assumed that it could be used as a drop in replacement for this, am i doing something wrong or has this function not yet been added? 

thank you for your help.

**Comment by svenstaro** [comment]
This should be supported already! Try the `-p` option.

**Comment by xpenguinclub** [comment]
nope... 
     wmfocus -p | xargs xkill -id
returns
    xkill:  invalid id "94191216841648"

**Comment by svenstaro** [comment]
Ok this is now fixed in release 1.1.1. It should now work as you'd expect.
