### ISSUE TITLE
error: linking with `cc` failed: exit status: 1

### ISSUE THREAD

**Issue by dopelDev** [svenstaro/wmfocus#104]
i can't compile error 

error: linking with `cc` failed: exit status: 1
  |
  = note: "cc" "-m64" "/tmp/cargo-installQem19I/release/deps/wmfocus-a6bed8931d9eb9fe.wmfocus.4408d5c2-cgu.0.rcgu.o" "-Wl,--as-needed" "-L" "/tmp/cargo-installQem19I/release/deps" "-L" "/usr/lib/x86_64-linux-gnu" "-L" "/usr/lib/x86_64-linux-gnu" "-L" "/usr/lib/x86_64-linux-gnu" "-L" "/usr/lib/x86_64-linux-gnu" "-L" "/home/dopel/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-Wl,--start-group" "-Wl,--end-group" "-Wl,-Bstatic" "/home/dopel/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcompiler_builtins-2882f53766b63f5c.rlib" "-Wl,-Bdynamic" "-lX11" "-lxcb-keysyms" "-lgobject-2.0" "-lglib-2.0" "-lcairo-gobject" "-lgobject-2.0" "-lglib-2.0" "-lcairo" "-lgobject-2.0" "-lglib-2.0" "-lxcb" "-lfontconfig" "-lfreetype" "-lexpat" "-lxkbcommon" "-lgcc_s" "-lutil" "-lrt" "-lpthread" "-lm" "-ldl" "-lc" "-Wl,--eh-frame-hdr" "-Wl,-znoexecstack" "-L" "/home/dopel/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-o" "/tmp/cargo-installQem19I/release/deps/wmfocus-a6bed8931d9eb9fe" "-Wl,--gc-sections" "-pie" "-Wl,-zrelro" "-Wl,-znow" "-Wl,-O1" "-nodefaultlibs"
  = note: /usr/bin/ld: cannot find -lxcb-keysyms
          collect2: error: ld returned 1 exit status

**Comment by svenstaro** [comment]
What's your distro?
