### ISSUE TITLE
Cargo.lock isn't being updated

### ISSUE THREAD

**Issue by colemickens** [svenstaro/wmfocus#11]
You can just peek the last commits to Cargo.toml and Cargo.lock and see that Cargo.lock isn't being updated properly.

(`wmfocus` itself appears in the lock file. Even in the 1.1.1 tag, it says 1.1.0 in the lock file.)

This breaks my ability to package for NixOS without patching to update Cargo.lock.

**Comment by svenstaro** [comment]
Good catch

**Comment by svenstaro** [comment]
Fixed now with a new signed tag.
