### ISSUE TITLE
Instantly pass characters to wmfocus

### ISSUE THREAD

**Issue by MDingas** [svenstaro/wmfocus#126]
It would be nice if there was a way to immediately pass characters into the program, for example:

```
wmfocus --input-character 'c' 
```

This would open wmfocus and input the character C. This would be helpful for me personally because when i know i want to go to the second tab, where N tabs are layered together, I could bind, let's say, ctrl + 2 to wmfocus -c '123456789' --input-character '2'.

I guess one would do it by passing keystrokes to X server, but what seems more hacky.

**Comment by markstos** [comment]
If you know exactly where you want to go, couldn't you make i3 or Sway IPC call to switch directly to the second tab?

Make an IPC call to return the JSON for the visible windows, use jq to process it to select the id of the second tab, then send the IPC command to focus that ID.

**Comment by markstos** [comment]
I recommend this issue be closed. With the IPC interfaces for i3 and Sway, it's already not that hard to script something like "focus the second window".
