### ISSUE TITLE
i3 focus_follows_mouse interferes with switching focus

### ISSUE THREAD

**Issue by bwinkler** [svenstaro/wmfocus#15]
I think this might be the same issue as #8 but I thought I would open a new one instead of bumping a closed issue. In i3 (version 4.16), when `focus_follows_mouse` is enabled and when the `wmfocus --fill` is used, focus seems to always stay on the window that contains the mouse cursor.

This also occurs without `--fill` if the mouse cursor happens to be in the region that the `wmfocus` hint window appears in. In the case of using `--fill`, this is the entire window and so it happens every time.

**Comment by svenstaro** [comment]
Can you give me a sure-fire way to reproduce this? I wasn't able to repro this before.

**Comment by bwinkler** [comment]
When `focus_follows_mouse` is enabled in i3, this happens pretty much consistently. Note that when you enable focus follows mouse, you have to reload i3, not just reload the config. Here's the minimal steps, anyway:
1. Enable `focus_follows_mouse` and reload i3.
2. Open two terminal windows and put the mouse cursor in the first terminal window.
3. Run `wmfocus --fill` and select the second terminal.

At this point, focus *should* be in the second window, however,it will actually be in whatever window had the mouse pointer (i.e. the first).

I've made a tentative fix in a pull request and I'll send it shortly. What I found was that there was a "mouse enter" event being generated when the hint windows were unmapped. Critically this event happened *after* `wmfocus` set the focus to the selected window so the mouse "entering" one of the other windows undid the focus set by `wmfocus`. You can see the commit message in the PR for more info.

I know nothing of Rust, so there is probably a better way to do it.

**Comment by Zeioth** [comment]
This behabior is normal, it also happen with i3-easyfocus. You have two options: disable focus_follows_mouse, or either don't move the mouse while you use wmfocus.

**Comment by markstos** [comment]
Given the comment by @Zeioth, I think this issue can be closed.
