### ISSUE TITLE
second key press registers only if first key is released

### ISSUE THREAD

**Issue by luminalle** [svenstaro/wmfocus#177]
I like it very much, but when selecting letters, if I don't type slowly, the second letter won't usually register.

I figured that if the first pressed key is not 100% released, while the second key is pressed, the second key press has no effect.

Not sure if this is as intended.

OS: Arch Linux x86_64
WM: i3-wm

is this how it is supposed to behave or is it just me?

**Comment by luminalle** [comment]
I kind of solved this with using "--chars asdfghjklzxcvbnmqwertyuiop" so each window gets unique char. Much better than having to select two letters anyway.

**Comment by svenstaro** [comment]
We could still try to fix this somehow. Might be easy.
