### ISSUE TITLE
Avoid using xkeysym::name

### ISSUE THREAD

**Issue by notgull** [svenstaro/wmfocus#257]
I was checking the dependents of some of my crates and I found this. I see that you use the `xkeysym::name()` function to get the name of the keyboard symbol and then use that, combined with user input, to analyze keystrokes. However, I really only intended the `name` function to be used for debugging. The output isn't stable and can change at any time (although it is very unlikely to).

I'm not sure if there is a real alternative, so feel free to close this issue if there isn't one. If there's anything I can add to `xkeysym` to help I would be happy to.

**Comment by svenstaro** [comment]
Hey, thanks for the concern. To be honest, the keysyms vex me greatly and I have yet to find a truly satisfying solution. I originally used xcb-util but that doesn't appear to be maintained at the moment.

I don't have any ideas about what could be truly done here. It comes down to this: the user provides a list of keys as printed on their keyboard and then wmfocus needs to listen for those keys bring pressed. Now I'm certainly no X-pert and there might be a better way but after some hours of relentless searching no better way emerged.

**Comment by notgull** [comment]
Fair enough. I suppose there isn't really a better solution. I'll close this issue.
