### ISSUE TITLE
i3wm: Focus tabbed windows?

### ISSUE THREAD

**Issue by snippins** [svenstaro/wmfocus#5]
I really like this since we can define how big the label is, however, unlike to i3-easyfocus, I can't focus a hidden tab if I use a tabbed container.

**Comment by svenstaro** [comment]
I don't quite understand. Could you post some screenshots or a how to to reproduce this?

**Comment by svenstaro** [comment]
Thanks! Do you want to take a stab at this?

**Comment by svenstaro** [comment]
Awesome! If you don't get around to it I might at some point perhaps but it's probably safer to scratch your own itch :P

**Comment by svenstaro** [comment]
So I just fixed this. Please do test it, though.
